import type { CardDefinition } from "./types.ts";

const SUN_EXPANSION_CARDS = [
  {
    id: "sun-lumen-page",
    name: "微光侍读",
    description: "守护晨祷书页的年轻学徒。",
    faction: "曜光",
    type: "unit",
    cost: 1,
    rarity: "普通",
    attack: 1,
    health: 3,
    traits: ["arcane"],
  },
  {
    id: "sun-glasswing-courier",
    name: "琉翼信使",
    description: "冲锋。它的羽翼会把捷报折射到整片天幕。",
    faction: "曜光",
    type: "unit",
    cost: 1,
    rarity: "普通",
    attack: 2,
    health: 1,
    keywords: ["charge"],
    traits: ["swift", "craft"],
  },
  {
    id: "sun-prism-squire",
    name: "棱镜扈从",
    description: "护盾。随身的折光甲仍带着工坊的温度。",
    faction: "曜光",
    type: "unit",
    cost: 2,
    rarity: "普通",
    attack: 2,
    health: 3,
    keywords: ["shield"],
    traits: ["bulwark", "craft"],
  },
  {
    id: "sun-horizon-hunter",
    name: "天际猎手",
    description: "沿着第一束晨光锁定远方猎物。",
    faction: "曜光",
    type: "unit",
    cost: 2,
    rarity: "普通",
    attack: 3,
    health: 2,
    traits: ["hunt"],
  },
  {
    id: "sun-choir-acolyte",
    name: "晨咏侍祭",
    description: "登场时，为一个友方角色恢复 2 点生命。",
    faction: "曜光",
    type: "unit",
    cost: 2,
    rarity: "稀有",
    attack: 2,
    health: 2,
    traits: ["arcane"],
    target: "friendly-character",
    onPlay: [{ kind: "heal", amount: 2 }],
  },
  {
    id: "sun-gilded-lancer",
    name: "鎏金枪骑",
    description: "冲锋。长枪掠过之处只留下灼亮的弧线。",
    faction: "曜光",
    type: "unit",
    cost: 3,
    rarity: "普通",
    attack: 4,
    health: 2,
    keywords: ["charge"],
    traits: ["swift", "hunt"],
  },
  {
    id: "sun-sunwell-artificer",
    name: "日井匠师",
    description: "护盾。她能把一缕日光锻造成坚实甲片。",
    faction: "曜光",
    type: "unit",
    cost: 3,
    rarity: "稀有",
    attack: 2,
    health: 4,
    keywords: ["shield"],
    traits: ["arcane", "craft"],
  },
  {
    id: "sun-aurora-duelist",
    name: "极昼决斗家",
    description: "激昂。每一次交锋都让她的剑芒更加炽烈。",
    faction: "曜光",
    type: "unit",
    cost: 3,
    rarity: "稀有",
    attack: 3,
    health: 4,
    keywords: ["fury"],
    traits: ["swift"],
  },
  {
    id: "sun-halo-captain",
    name: "光环卫队长",
    description: "嘲讽。身后的光轮标示着不可后退的阵线。",
    faction: "曜光",
    type: "unit",
    cost: 4,
    rarity: "普通",
    attack: 4,
    health: 5,
    keywords: ["taunt"],
    traits: ["bulwark"],
  },
  {
    id: "sun-whitefire-priest",
    name: "白焰司祭",
    description: "汲取。净化之火也会回馈执炬之人。",
    faction: "曜光",
    type: "unit",
    cost: 4,
    rarity: "史诗",
    attack: 3,
    health: 5,
    keywords: ["lifesteal"],
    traits: ["arcane"],
  },
  {
    id: "sun-prism-huntress",
    name: "虹棱女猎手",
    description: "她用分光箭矢封锁猎物的每条退路。",
    faction: "曜光",
    type: "unit",
    cost: 4,
    rarity: "稀有",
    attack: 5,
    health: 4,
    traits: ["hunt", "craft"],
  },
  {
    id: "sun-zenith-golem",
    name: "正午晶铠像",
    description: "嘲讽，护盾。正午时分，它的晶甲坚不可摧。",
    faction: "曜光",
    type: "unit",
    cost: 5,
    rarity: "史诗",
    attack: 4,
    health: 7,
    keywords: ["taunt", "shield"],
    traits: ["bulwark", "craft"],
  },
  {
    id: "sun-radiant-griffin",
    name: "辉穹狮鹫",
    description: "冲锋。它从云层俯冲时宛如坠落的太阳。",
    faction: "曜光",
    type: "unit",
    cost: 5,
    rarity: "史诗",
    attack: 6,
    health: 4,
    keywords: ["charge"],
    traits: ["swift", "hunt"],
  },
  {
    id: "sun-corona-archon",
    name: "日冕执政官",
    description: "汲取。古老光誓在他的冠冕中循环不息。",
    faction: "曜光",
    type: "unit",
    cost: 6,
    rarity: "史诗",
    attack: 6,
    health: 7,
    keywords: ["lifesteal"],
    traits: ["arcane", "bulwark"],
  },
  {
    id: "sun-daystar-titan",
    name: "曜日泰坦",
    description: "嘲讽，激昂。沉睡的太阳引擎终于再次迈步。",
    faction: "曜光",
    type: "unit",
    cost: 8,
    rarity: "传说",
    attack: 8,
    health: 10,
    keywords: ["taunt", "fury"],
    traits: ["bulwark", "craft"],
  },
  {
    id: "sun-flare-spark",
    name: "耀斑火种",
    description: "对一个敌方角色造成 1 点伤害。一点强光足以暴露破绽。",
    faction: "曜光",
    type: "spell",
    cost: 0,
    rarity: "普通",
    school: "radiance",
    target: "enemy-character",
    effect: [{ kind: "damage", amount: 1 }],
  },
  {
    id: "sun-refraction-aid",
    name: "折光援护",
    description: "为一个友方角色恢复 3 点生命。折射的暖光会封住伤口。",
    faction: "曜光",
    type: "spell",
    cost: 1,
    rarity: "普通",
    school: "radiance",
    target: "friendly-character",
    effect: [{ kind: "heal", amount: 3 }],
  },
  {
    id: "sun-mirror-tempering",
    name: "镜甲淬炼",
    description: "使一个友方单位获得 +1/+2。",
    faction: "曜光",
    type: "spell",
    cost: 2,
    rarity: "普通",
    school: "radiance",
    target: "friendly-unit",
    effect: [{ kind: "buff", attack: 1, health: 2 }],
  },
  {
    id: "sun-orbit-insight",
    name: "环日启示",
    description: "发现一张曜光卡牌。",
    faction: "曜光",
    type: "spell",
    cost: 2,
    rarity: "稀有",
    school: "radiance",
    target: "none",
    keywords: ["discover"],
    effect: [{
      kind: "discover",
      choices: ["sun-dawn-scout", "sun-mirror-warden", "sun-focused-ray"],
    }],
  },
  {
    id: "sun-spear-descent",
    name: "天枪坠击",
    description: "对一个敌方单位造成 4 点伤害。",
    faction: "曜光",
    type: "spell",
    cost: 3,
    rarity: "稀有",
    school: "radiance",
    target: "enemy-unit",
    effect: [{ kind: "damage", amount: 4 }],
  },
  {
    id: "sun-dawn-muster",
    name: "晨阵集结",
    description: "奥秘：当敌方单位攻击你的核心时，对其造成 3 点伤害。",
    faction: "曜光",
    type: "spell",
    cost: 4,
    rarity: "史诗",
    school: "radiance",
    target: "none",
    keywords: ["secret"],
    effect: [{
      kind: "secret",
      secretId: "sun-dawn-muster",
      trigger: "opponent-attacks-hero",
      effect: { kind: "damage-attacker", amount: 3 },
    }],
  },
  {
    id: "sun-supernova-judgment",
    name: "新星裁决刃",
    description: "武器：6 点攻击，2 点耐久。",
    faction: "曜光",
    type: "weapon",
    cost: 6,
    rarity: "史诗",
    attack: 6,
    durability: 2,
  },
] as const satisfies readonly CardDefinition[];

const VOID_EXPANSION_CARDS = [
  {
    id: "void-brine-skulker",
    name: "盐雾伏游者",
    description: "在潮痕之间出没的浅海伏击者。",
    faction: "幽潮",
    type: "unit",
    cost: 1,
    rarity: "普通",
    attack: 2,
    health: 2,
    traits: ["hunt"],
  },
  {
    id: "void-duskfin-darter",
    name: "暮鳍疾刺",
    description: "冲锋。暮色落水前，它已经刺穿第一道浪。",
    faction: "幽潮",
    type: "unit",
    cost: 1,
    rarity: "普通",
    attack: 2,
    health: 1,
    keywords: ["charge"],
    traits: ["swift"],
  },
  {
    id: "void-shellback-sentinel",
    name: "覆壳哨卫",
    description: "嘲讽。它用沉重背壳堵住狭窄的礁道。",
    faction: "幽潮",
    type: "unit",
    cost: 2,
    rarity: "普通",
    attack: 1,
    health: 5,
    keywords: ["taunt"],
    traits: ["bulwark"],
  },
  {
    id: "void-inkveil-oracle",
    name: "墨帷先知",
    description: "登场时抽一张牌。她在墨云中读见下一股暗流。",
    faction: "幽潮",
    type: "unit",
    cost: 2,
    rarity: "稀有",
    attack: 2,
    health: 2,
    traits: ["arcane"],
    onPlay: [{ kind: "draw", count: 1 }],
  },
  {
    id: "void-siphon-lamprey",
    name: "噬流七鳃鳗",
    description: "汲取。它追逐的不是血，而是目标体内的魔潮。",
    faction: "幽潮",
    type: "unit",
    cost: 2,
    rarity: "稀有",
    attack: 2,
    health: 3,
    keywords: ["lifesteal"],
    traits: ["hunt"],
  },
  {
    id: "void-coral-mimic",
    name: "蚀珊瑚拟态",
    description: "护盾。静止时，它与幽暗礁石毫无区别。",
    faction: "幽潮",
    type: "unit",
    cost: 3,
    rarity: "普通",
    attack: 3,
    health: 4,
    keywords: ["shield"],
    traits: ["craft"],
  },
  {
    id: "void-riptide-duelist",
    name: "裂潮斗士",
    description: "激昂。越猛烈的浪头越能激起他的战意。",
    faction: "幽潮",
    type: "unit",
    cost: 3,
    rarity: "稀有",
    attack: 3,
    health: 4,
    keywords: ["fury"],
    traits: ["swift", "hunt"],
  },
  {
    id: "void-trench-mender",
    name: "海沟缝合师",
    description: "登场时，为一个友方角色恢复 3 点生命。",
    faction: "幽潮",
    type: "unit",
    cost: 3,
    rarity: "稀有",
    attack: 2,
    health: 4,
    traits: ["arcane", "craft"],
    target: "friendly-character",
    onPlay: [{ kind: "heal", amount: 3 }],
  },
  {
    id: "void-razorfin-corsair",
    name: "刃鳍掠夺者",
    description: "冲锋。骨刃切开的浪花会替它掩护突进。",
    faction: "幽潮",
    type: "unit",
    cost: 4,
    rarity: "普通",
    attack: 5,
    health: 3,
    keywords: ["charge"],
    traits: ["swift", "hunt"],
  },
  {
    id: "void-murkplate-hermit",
    name: "玄甲寄居者",
    description: "嘲讽，护盾。它背负着一座沉没神殿的残门。",
    faction: "幽潮",
    type: "unit",
    cost: 4,
    rarity: "史诗",
    attack: 3,
    health: 6,
    keywords: ["taunt", "shield"],
    traits: ["bulwark", "craft"],
  },
  {
    id: "void-abyssal-chanter",
    name: "深渊吟潮者",
    description: "汲取。低沉潮歌会从敌人身上带回生命。",
    faction: "幽潮",
    type: "unit",
    cost: 4,
    rarity: "史诗",
    attack: 4,
    health: 5,
    keywords: ["lifesteal"],
    traits: ["arcane"],
  },
  {
    id: "void-moonjaw-shark",
    name: "月颚猎鲨",
    description: "激昂。银白牙列会在每次受击后咬得更深。",
    faction: "幽潮",
    type: "unit",
    cost: 5,
    rarity: "稀有",
    attack: 5,
    health: 6,
    keywords: ["fury"],
    traits: ["hunt"],
  },
  {
    id: "void-drowned-leviathan",
    name: "溺忆海兽",
    description: "嘲讽。它的呼吸携带着失落舰队的回声。",
    faction: "幽潮",
    type: "unit",
    cost: 6,
    rarity: "史诗",
    attack: 6,
    health: 8,
    keywords: ["taunt"],
    traits: ["bulwark", "arcane"],
  },
  {
    id: "void-tempest-manta",
    name: "暴潮魔鬼鱼",
    description: "冲锋，护盾。它把雷云披在宽阔双翼之上。",
    faction: "幽潮",
    type: "unit",
    cost: 6,
    rarity: "史诗",
    attack: 7,
    health: 5,
    keywords: ["charge", "shield"],
    traits: ["swift", "craft"],
  },
  {
    id: "void-thalassic-sovereign",
    name: "幽海无冠王",
    description: "汲取，激昂。整片深海都在等待它重新加冕。",
    faction: "幽潮",
    type: "unit",
    cost: 8,
    rarity: "传说",
    attack: 9,
    health: 9,
    keywords: ["lifesteal", "fury"],
    traits: ["arcane", "hunt"],
  },
  {
    id: "void-saltbite",
    name: "盐蚀咬痕",
    description: "对一个敌方角色造成 1 点伤害。",
    faction: "幽潮",
    type: "spell",
    cost: 0,
    rarity: "普通",
    school: "tide",
    target: "enemy-character",
    effect: [{ kind: "damage", amount: 1 }],
  },
  {
    id: "void-deepwater-draught",
    name: "深水汲饮",
    description: "为一个友方角色恢复 3 点生命。",
    faction: "幽潮",
    type: "spell",
    cost: 1,
    rarity: "普通",
    school: "tide",
    target: "friendly-character",
    effect: [{ kind: "heal", amount: 3 }],
  },
  {
    id: "void-pressure-spike",
    name: "压潮尖刺",
    description: "对一个敌方单位造成 3 点伤害。",
    faction: "幽潮",
    type: "spell",
    cost: 2,
    rarity: "普通",
    school: "tide",
    target: "enemy-unit",
    effect: [{ kind: "damage", amount: 3 }],
  },
  {
    id: "void-echoing-current",
    name: "回响暗流",
    description: "奥秘：当敌方施放战术时，抽两张牌。",
    faction: "幽潮",
    type: "spell",
    cost: 2,
    rarity: "稀有",
    school: "tide",
    target: "none",
    keywords: ["secret"],
    effect: [{
      kind: "secret",
      secretId: "void-echoing-current",
      trigger: "opponent-plays-spell",
      effect: { kind: "draw", count: 2 },
    }],
  },
  {
    id: "void-moonpool-mutation",
    name: "月池异变",
    description: "发现一张幽潮卡牌。",
    faction: "幽潮",
    type: "spell",
    cost: 3,
    rarity: "稀有",
    school: "tide",
    target: "none",
    keywords: ["discover"],
    effect: [{
      kind: "discover",
      choices: ["void-mist-lurker", "void-undertow-guard", "void-chill-needle"],
    }],
  },
  {
    id: "void-blackwake-torpedo",
    name: "黑浪鱼雷",
    description: "对一个敌方角色造成 5 点伤害。",
    faction: "幽潮",
    type: "spell",
    cost: 4,
    rarity: "史诗",
    school: "tide",
    target: "enemy-character",
    effect: [{ kind: "damage", amount: 5 }],
  },
  {
    id: "void-maelstrom-memory",
    name: "漩涡钩镰",
    description: "武器：5 点攻击，3 点耐久。",
    faction: "幽潮",
    type: "weapon",
    cost: 7,
    rarity: "史诗",
    attack: 5,
    durability: 3,
  },
] as const satisfies readonly CardDefinition[];

const NEUTRAL_EXPANSION_CARDS = [
  {
    id: "neutral-lantern-mouse",
    name: "绒鼠引路",
    description: "抽一张牌。提灯绒鼠会把旅人带向仍亮着灯的驿站。",
    faction: "中立",
    type: "spell",
    cost: 1,
    rarity: "普通",
    school: "construct",
    target: "none",
    effect: [{ kind: "draw", count: 1 }],
  },
  {
    id: "neutral-windstep-messenger",
    name: "踏风报信人",
    description: "冲锋。他总能比坏消息更早抵达。",
    faction: "中立",
    type: "unit",
    cost: 1,
    rarity: "普通",
    attack: 2,
    health: 1,
    keywords: ["charge"],
    traits: ["swift"],
  },
  {
    id: "neutral-ironpot-cook",
    name: "铁锅行厨",
    description: "登场时，为一个友方角色恢复 2 点生命。热汤先到，伤药随后。",
    faction: "中立",
    type: "unit",
    cost: 2,
    rarity: "普通",
    attack: 2,
    health: 3,
    traits: ["craft"],
    target: "friendly-character",
    onPlay: [{ kind: "heal", amount: 2 }],
  },
  {
    id: "neutral-brassback-badger",
    name: "铜背獾",
    description: "嘲讽。商旅们都知道不要惊醒守车的它。",
    faction: "中立",
    type: "unit",
    cost: 2,
    rarity: "普通",
    attack: 2,
    health: 4,
    keywords: ["taunt"],
    traits: ["bulwark"],
  },
  {
    id: "neutral-relic-appraiser",
    name: "遗物估价师",
    description: "法术伤害 +1。登场时抽一张牌。真品的故事往往比价格更高。",
    faction: "中立",
    type: "unit",
    cost: 2,
    rarity: "稀有",
    attack: 2,
    health: 2,
    traits: ["arcane"],
    spellDamage: 1,
    onPlay: [{ kind: "draw", count: 1 }],
  },
  {
    id: "neutral-riveted-ram",
    name: "铆钉撞角羊",
    description: "护盾。工匠们给它装上了真正的攻城护额。",
    faction: "中立",
    type: "unit",
    cost: 3,
    rarity: "普通",
    attack: 3,
    health: 4,
    keywords: ["shield"],
    traits: ["craft", "bulwark"],
  },
  {
    id: "neutral-crossroad-duelist",
    name: "岔路决斗客",
    description: "激昂。他在每一个路口都能找到新的对手。",
    faction: "中立",
    type: "unit",
    cost: 3,
    rarity: "稀有",
    attack: 3,
    health: 4,
    keywords: ["fury"],
    traits: ["swift"],
  },
  {
    id: "neutral-dune-tracker",
    name: "沙迹追猎者",
    description: "冲锋。没有足印能逃过他掌中的铜盘。",
    faction: "中立",
    type: "unit",
    cost: 3,
    rarity: "稀有",
    attack: 4,
    health: 2,
    keywords: ["charge"],
    traits: ["swift", "hunt"],
  },
  {
    id: "neutral-aether-peddler",
    name: "以太货郎",
    description: "汲取。他出售的瓶装魔力总会悄悄回流。",
    faction: "中立",
    type: "unit",
    cost: 4,
    rarity: "稀有",
    attack: 4,
    health: 4,
    keywords: ["lifesteal"],
    traits: ["arcane"],
  },
  {
    id: "neutral-bastion-tortoise",
    name: "驮垒巨龟",
    description: "嘲讽。它背上的小型堡垒从未失守。",
    faction: "中立",
    type: "unit",
    cost: 4,
    rarity: "普通",
    attack: 3,
    health: 7,
    keywords: ["taunt"],
    traits: ["bulwark"],
  },
  {
    id: "neutral-gearhawk-handler",
    name: "齿隼驯养师",
    description: "护盾。她和机械猎隼共用一套警戒视野。",
    faction: "中立",
    type: "unit",
    cost: 4,
    rarity: "史诗",
    attack: 4,
    health: 5,
    keywords: ["shield"],
    traits: ["hunt", "craft"],
  },
  {
    id: "neutral-ruin-stag",
    name: "遗迹冠鹿",
    description: "激昂。古代符文会回应它踏碎石板的轰鸣。",
    faction: "中立",
    type: "unit",
    cost: 5,
    rarity: "史诗",
    attack: 5,
    health: 6,
    keywords: ["fury"],
    traits: ["arcane", "hunt"],
  },
  {
    id: "neutral-mobile-forge",
    name: "自走熔铸炉",
    description: "嘲讽，护盾。四条机械腿让整座工坊随军前进。",
    faction: "中立",
    type: "unit",
    cost: 6,
    rarity: "史诗",
    attack: 5,
    health: 8,
    keywords: ["taunt", "shield"],
    traits: ["bulwark", "craft"],
  },
  {
    id: "neutral-cloudrail-behemoth",
    name: "云轨冲撞令",
    description: "对一个敌方角色造成 7 点伤害。重新启动废弃天轨的代价十分昂贵。",
    faction: "中立",
    type: "spell",
    cost: 6,
    rarity: "史诗",
    school: "construct",
    target: "enemy-character",
    effect: [{ kind: "damage", amount: 7 }],
  },
  {
    id: "neutral-worldroad-colossus",
    name: "万途驮城者",
    description: "嘲讽，汲取。无数商路最终汇聚在它背负的城邦。",
    faction: "中立",
    type: "unit",
    cost: 8,
    rarity: "传说",
    attack: 8,
    health: 11,
    keywords: ["taunt", "lifesteal"],
    traits: ["bulwark", "arcane"],
  },
  {
    id: "neutral-pocket-remedy",
    name: "行囊急救剂",
    description: "为一个友方角色恢复 2 点生命。",
    faction: "中立",
    type: "spell",
    cost: 0,
    rarity: "普通",
    school: "construct",
    target: "friendly-character",
    effect: [{ kind: "heal", amount: 2 }],
  },
  {
    id: "neutral-springtrap",
    name: "便携弹簧阱",
    description: "奥秘：当敌方单位攻击你的核心时，对其造成 2 点伤害。",
    faction: "中立",
    type: "spell",
    cost: 1,
    rarity: "普通",
    school: "construct",
    target: "none",
    keywords: ["secret"],
    effect: [{
      kind: "secret",
      secretId: "neutral-springtrap",
      trigger: "opponent-attacks-hero",
      effect: { kind: "damage-attacker", amount: 2 },
    }],
  },
  {
    id: "neutral-field-reinforcement",
    name: "野战加固",
    description: "使一个友方单位获得 +1/+3。",
    faction: "中立",
    type: "spell",
    cost: 2,
    rarity: "普通",
    school: "construct",
    target: "friendly-unit",
    effect: [{ kind: "buff", attack: 1, health: 3 }],
  },
  {
    id: "neutral-route-ledger",
    name: "通途账册",
    description: "发现一张中立卡牌。账册记得每处补给站。",
    faction: "中立",
    type: "spell",
    cost: 2,
    rarity: "稀有",
    school: "construct",
    target: "none",
    keywords: ["discover"],
    effect: [{ kind: "discover", choices: ["neutral-moss-runner", "neutral-clockwork-beetle", "neutral-tactical-map"] }],
  },
  {
    id: "neutral-calibrated-bolt",
    name: "校准弩炮",
    description: "对一个敌方角色造成 4 点伤害。连击：额外造成 2 点伤害。",
    faction: "中立",
    type: "spell",
    cost: 3,
    rarity: "稀有",
    school: "construct",
    target: "enemy-character",
    effect: [{ kind: "damage", amount: 4 }],
    combo: [{ kind: "damage", amount: 2 }],
  },
  {
    id: "neutral-masterwork-plating",
    name: "大师级覆甲",
    description: "使一个友方单位获得 +3/+4。",
    faction: "中立",
    type: "spell",
    cost: 5,
    rarity: "史诗",
    school: "construct",
    target: "friendly-unit",
    effect: [{ kind: "buff", attack: 3, health: 4 }],
  },
  {
    id: "neutral-grand-expedition",
    name: "远征合金刃",
    description: "武器：3 点攻击，3 点耐久。",
    faction: "中立",
    type: "weapon",
    cost: 7,
    rarity: "史诗",
    attack: 3,
    durability: 3,
  },
] as const satisfies readonly CardDefinition[];

export const CORE_EXPANSION_CARDS: readonly CardDefinition[] = Object.freeze([
  ...SUN_EXPANSION_CARDS,
  ...VOID_EXPANSION_CARDS,
  ...NEUTRAL_EXPANSION_CARDS,
]);
