import type { CardDefinition } from "./types.ts";

export const EMBER_ASTRAL_CARDS: readonly CardDefinition[] = Object.freeze([
  // 烬火：20 个单位。强调抢节奏、冲锋、激昂与直接伤害。
  {
    id: "ember-cinder-scout",
    name: "火星斥候",
    description: "冲锋。踏过的焦土会替后来者标出进攻路线。",
    faction: "烬火",
    type: "unit",
    cost: 1,
    rarity: "普通",
    attack: 2,
    health: 1,
    keywords: ["charge"],
    traits: ["swift", "hunt"],
  },
  {
    id: "ember-coalfang-pup",
    name: "炭牙幼兽",
    description: "激昂。每一次交锋都让它体内的火种更加旺盛。",
    faction: "烬火",
    type: "unit",
    cost: 1,
    rarity: "普通",
    attack: 1,
    health: 3,
    keywords: ["fury"],
    traits: ["hunt"],
  },
  {
    id: "ember-ash-forager",
    name: "灰烬搜寻者",
    description: "登场时，对一个随机敌方角色造成 1 点伤害。它总能从余烬里翻出仍可利用的火星。",
    faction: "烬火",
    type: "unit",
    cost: 2,
    rarity: "普通",
    attack: 2,
    health: 2,
    traits: ["craft", "hunt"],
    onPlay: [{ kind: "random-enemy-damage", amount: 1 }],
  },
  {
    id: "ember-blade-acolyte",
    name: "炽刃侍从",
    description: "激昂。她用每一道新伤痕校准下一次挥击。",
    faction: "烬火",
    type: "unit",
    cost: 2,
    rarity: "普通",
    attack: 3,
    health: 2,
    keywords: ["fury"],
    traits: ["swift"],
  },
  {
    id: "ember-charrock-guard",
    name: "焦岩卫士",
    description: "嘲讽。冷却的岩壳之下仍有熔流奔涌。",
    faction: "烬火",
    type: "unit",
    cost: 2,
    rarity: "普通",
    attack: 2,
    health: 4,
    keywords: ["taunt"],
    traits: ["bulwark"],
  },
  {
    id: "ember-flamespine-vanguard",
    name: "焰脊先锋",
    description: "冲锋。号角尚未落音，他已经越过战线。",
    faction: "烬火",
    type: "unit",
    cost: 3,
    rarity: "普通",
    attack: 3,
    health: 3,
    keywords: ["charge"],
    traits: ["swift", "hunt"],
  },
  {
    id: "ember-forge-smith",
    name: "熔炉铸师",
    description: "登场时，使一个友方单位获得 +1/+1。",
    faction: "烬火",
    type: "unit",
    cost: 3,
    rarity: "稀有",
    attack: 3,
    health: 4,
    traits: ["craft"],
    target: "friendly-unit",
    onPlay: [{ kind: "buff", attack: 1, health: 1 }],
  },
  {
    id: "ember-heart-drinker",
    name: "焰心汲能者",
    description: "汲取。它把敌人的余温重新炼入自己的核心。",
    faction: "烬火",
    type: "unit",
    cost: 3,
    rarity: "稀有",
    attack: 3,
    health: 3,
    keywords: ["lifesteal"],
    traits: ["arcane", "hunt"],
  },
  {
    id: "ember-slag-sentinel",
    name: "炉渣哨兵",
    description: "嘲讽，护盾。由熔炉废料压铸成的移动壁垒。",
    faction: "烬火",
    type: "unit",
    cost: 4,
    rarity: "稀有",
    attack: 3,
    health: 5,
    keywords: ["taunt", "shield"],
    traits: ["bulwark", "craft"],
  },
  {
    id: "ember-crimson-duelist",
    name: "赤焰决斗家",
    description: "激昂。她只承认从正面赢下的胜利。",
    faction: "烬火",
    type: "unit",
    cost: 4,
    rarity: "稀有",
    attack: 5,
    health: 4,
    keywords: ["fury"],
    traits: ["swift"],
  },
  {
    id: "ember-magma-hornbeast",
    name: "熔角战兽",
    description: "登场时，对一个随机敌方角色造成 1 点伤害。它用滚烫长角犁开阵线。",
    faction: "烬火",
    type: "unit",
    cost: 4,
    rarity: "普通",
    attack: 4,
    health: 5,
    traits: ["hunt", "bulwark"],
    onPlay: [{ kind: "random-enemy-damage", amount: 1 }],
  },
  {
    id: "ember-oath-pyromancer",
    name: "焚誓祭司",
    description: "登场时，对一个敌方角色造成 2 点伤害。",
    faction: "烬火",
    type: "unit",
    cost: 5,
    rarity: "稀有",
    attack: 4,
    health: 5,
    traits: ["arcane"],
    target: "enemy-character",
    onPlay: [{ kind: "damage", amount: 2 }],
  },
  {
    id: "ember-volcanic-ram",
    name: "火山冲角兽",
    description: "冲锋。它的角尖总比熔岩前沿更早抵达。",
    faction: "烬火",
    type: "unit",
    cost: 5,
    rarity: "稀有",
    attack: 6,
    health: 5,
    keywords: ["charge"],
    traits: ["swift", "hunt"],
  },
  {
    id: "ember-heatbound-colossus",
    name: "炽铠巨像",
    description: "嘲讽。每块甲片都封存着一座旧熔炉的热量。",
    faction: "烬火",
    type: "unit",
    cost: 6,
    rarity: "普通",
    attack: 6,
    health: 8,
    keywords: ["taunt"],
    traits: ["bulwark", "craft"],
  },
  {
    id: "ember-ashwing-phoenix",
    name: "灰翼不死鸟",
    description: "冲锋，护盾。第一层灰烬只是它的新生外壳。",
    faction: "烬火",
    type: "unit",
    cost: 6,
    rarity: "史诗",
    attack: 6,
    health: 5,
    keywords: ["charge", "shield"],
    traits: ["swift", "arcane"],
  },
  {
    id: "ember-war-drummer",
    name: "燎原战鼓手",
    description: "登场时，使一个友方单位获得 +2 攻击。",
    faction: "烬火",
    type: "unit",
    cost: 4,
    rarity: "稀有",
    attack: 3,
    health: 5,
    traits: ["craft", "swift"],
    target: "friendly-unit",
    onPlay: [{ kind: "buff", attack: 2, health: 0 }],
  },
  {
    id: "ember-scorchland-hydra",
    name: "灼地多首兽",
    description: "激昂。登场时，对一个随机敌方角色造成 3 点伤害。",
    faction: "烬火",
    type: "unit",
    cost: 7,
    rarity: "史诗",
    attack: 7,
    health: 7,
    keywords: ["fury"],
    traits: ["hunt"],
    onPlay: [{ kind: "random-enemy-damage", amount: 3 }],
  },
  {
    id: "ember-forgecrown-general",
    name: "炉冠统领",
    description: "冲锋，激昂。登场时抽一张牌。",
    faction: "烬火",
    type: "unit",
    cost: 7,
    rarity: "传说",
    attack: 7,
    health: 8,
    keywords: ["charge", "fury"],
    traits: ["swift", "craft"],
    onPlay: [{ kind: "draw", count: 1 }],
  },
  {
    id: "ember-caldera-core",
    name: "地心焰核",
    description: "嘲讽，护盾。登场时，对一个随机敌方角色造成 4 点伤害。",
    faction: "烬火",
    type: "unit",
    cost: 8,
    rarity: "传说",
    attack: 8,
    health: 10,
    keywords: ["taunt", "shield"],
    traits: ["bulwark", "arcane"],
    onPlay: [{ kind: "random-enemy-damage", amount: 4 }],
  },
  {
    id: "ember-spark-artificer",
    name: "余烬工程师",
    description: "登场时抽一张牌。她能从将熄的火堆里拆出完整零件。",
    faction: "烬火",
    type: "unit",
    cost: 3,
    rarity: "史诗",
    attack: 2,
    health: 4,
    traits: ["craft", "arcane"],
    onPlay: [{ kind: "draw", count: 1 }],
  },

  // 烬火：10 张战术。
  {
    id: "ember-leaping-spark",
    name: "跳火",
    description: "对一个敌方角色造成 1 点伤害。最小的火星也知道该往哪里落。",
    faction: "烬火",
    type: "spell",
    cost: 0,
    rarity: "普通",
    school: "ember",
    target: "enemy-character",
    effect: [{ kind: "damage", amount: 1 }],
  },
  {
    id: "ember-flame-pierce",
    name: "烈焰穿刺",
    description: "对一个敌方角色造成 2 点伤害。热浪会替矛尖完成最后一寸突进。",
    faction: "烬火",
    type: "spell",
    cost: 1,
    rarity: "普通",
    school: "ember",
    target: "enemy-character",
    effect: [{ kind: "damage", amount: 2 }],
  },
  {
    id: "ember-ignite-morale",
    name: "战意点燃",
    description: "使一个友方单位获得 +2/+1。",
    faction: "烬火",
    type: "spell",
    cost: 2,
    rarity: "普通",
    school: "ember",
    target: "friendly-unit",
    effect: [{ kind: "buff", attack: 2, health: 1 }],
  },
  {
    id: "ember-cinder-dispatch",
    name: "余烬急报",
    description: "抽一张牌，并对一个随机敌方角色造成 1 点伤害。",
    faction: "烬火",
    type: "spell",
    cost: 2,
    rarity: "稀有",
    school: "ember",
    target: "none",
    effect: [
      { kind: "draw", count: 1 },
      { kind: "random-enemy-damage", amount: 1 },
    ],
  },
  {
    id: "ember-fireline-lockdown",
    name: "火线封锁",
    description: "奥秘：当敌方召唤单位时，对敌方核心造成 2 点伤害。",
    faction: "烬火",
    type: "spell",
    cost: 3,
    rarity: "普通",
    school: "ember",
    target: "none",
    keywords: ["secret"],
    effect: [{
      kind: "secret",
      secretId: "ember-fireline-lockdown",
      trigger: "opponent-summons-unit",
      effect: { kind: "damage-enemy-hero", amount: 2 },
    }],
  },
  {
    id: "ember-ash-rekindling",
    name: "灰烬再燃",
    description: "召唤两个火星斥候。",
    faction: "烬火",
    type: "spell",
    cost: 3,
    rarity: "稀有",
    school: "ember",
    target: "none",
    effect: [{ kind: "summon", cardId: "ember-cinder-scout", count: 2 }],
  },
  {
    id: "ember-molten-core-overload",
    name: "熔芯过载",
    description: "过载（1）：使一个友方单位获得 +3/+3。稳定运转从来不是它的设计目标。",
    faction: "烬火",
    type: "spell",
    cost: 4,
    rarity: "稀有",
    school: "ember",
    target: "friendly-unit",
    overload: 1,
    effect: [{ kind: "buff", attack: 3, health: 3 }],
  },
  {
    id: "ember-cinder-rain",
    name: "烬雨齐射",
    description: "发现一张烬火卡牌。",
    faction: "烬火",
    type: "spell",
    cost: 5,
    rarity: "史诗",
    school: "ember",
    target: "none",
    keywords: ["discover"],
    effect: [{ kind: "discover", choices: ["ember-leaping-spark", "ember-flame-pierce", "ember-ignite-morale"] }],
  },
  {
    id: "ember-calamity-verdict",
    name: "灾火审判",
    description: "对一个敌方角色造成 6 点伤害。",
    faction: "烬火",
    type: "spell",
    cost: 6,
    rarity: "史诗",
    school: "ember",
    target: "enemy-character",
    effect: [{ kind: "damage", amount: 6 }],
  },
  {
    id: "ember-red-lotus-finale",
    name: "红莲焚刃",
    description: "武器：8 点攻击，2 点耐久。",
    faction: "烬火",
    type: "weapon",
    cost: 8,
    rarity: "史诗",
    attack: 8,
    durability: 2,
  },

  // 星穹：20 个单位。强调护盾、续航、抽牌与秘契联动。
  {
    id: "astral-stardust-familiar",
    name: "星尘伴灵",
    description: "护盾。它把主人遗漏的愿望藏在微光里。",
    faction: "星穹",
    type: "unit",
    cost: 1,
    rarity: "普通",
    attack: 1,
    health: 2,
    keywords: ["shield"],
    traits: ["arcane"],
  },
  {
    id: "astral-skychart-apprentice",
    name: "天图学徒",
    description: "登场时抽一张牌。她总能在星图边缘发现新航路。",
    faction: "星穹",
    type: "unit",
    cost: 1,
    rarity: "稀有",
    attack: 1,
    health: 1,
    traits: ["arcane"],
    onPlay: [{ kind: "draw", count: 1 }],
  },
  {
    id: "astral-prism-guard",
    name: "棱镜守卫",
    description: "护盾。折射装甲会把第一道威胁散入星幕。",
    faction: "星穹",
    type: "unit",
    cost: 2,
    rarity: "普通",
    attack: 1,
    health: 4,
    keywords: ["shield"],
    traits: ["bulwark"],
  },
  {
    id: "astral-comet-scribe",
    name: "彗迹抄录员",
    description: "登场时抽一张牌。彗尾是宇宙写给她的速记。",
    faction: "星穹",
    type: "unit",
    cost: 2,
    rarity: "普通",
    attack: 2,
    health: 2,
    traits: ["arcane"],
    onPlay: [{ kind: "draw", count: 1 }],
  },
  {
    id: "astral-orbit-moonhare",
    name: "环轨月兔",
    description: "护盾。它沿着看不见的轨道跳过危险。",
    faction: "星穹",
    type: "unit",
    cost: 2,
    rarity: "普通",
    attack: 2,
    health: 3,
    keywords: ["shield"],
    traits: ["swift"],
  },
  {
    id: "astral-veil-seer",
    name: "星幕先知",
    description: "汲取。她从遥远星光中借来尚未消逝的生命。",
    faction: "星穹",
    type: "unit",
    cost: 3,
    rarity: "稀有",
    attack: 2,
    health: 4,
    keywords: ["lifesteal"],
    traits: ["arcane"],
  },
  {
    id: "astral-mirror-adept",
    name: "镜宙修习者",
    description: "护盾。她在镜面宇宙里预演每一次受击。",
    faction: "星穹",
    type: "unit",
    cost: 3,
    rarity: "普通",
    attack: 3,
    health: 3,
    keywords: ["shield"],
    traits: ["craft"],
  },
  {
    id: "astral-constellation-gardener",
    name: "星座园丁",
    description: "登场时，为一个友方角色恢复 2 点生命。她把暗淡星辰修剪成新的航标。",
    faction: "星穹",
    type: "unit",
    cost: 3,
    rarity: "稀有",
    attack: 2,
    health: 5,
    traits: ["arcane", "bulwark"],
    target: "friendly-character",
    onPlay: [{ kind: "heal", amount: 2 }],
  },
  {
    id: "astral-nebula-knight",
    name: "星云骑士",
    description: "嘲讽。她的披风展开时，就像一道横贯夜空的城墙。",
    faction: "星穹",
    type: "unit",
    cost: 4,
    rarity: "普通",
    attack: 4,
    health: 5,
    keywords: ["taunt"],
    traits: ["bulwark"],
  },
  {
    id: "astral-archive-stargazer",
    name: "秘库观星官",
    description: "登场时抽一张牌。封存的每颗星都是一条可调用的档案。",
    faction: "星穹",
    type: "unit",
    cost: 4,
    rarity: "稀有",
    attack: 3,
    health: 4,
    traits: ["arcane", "craft"],
    onPlay: [{ kind: "draw", count: 1 }],
  },
  {
    id: "astral-eclipse-stalker",
    name: "食影巡猎者",
    description: "汲取。它只在两颗月亮同时沉没时现身。",
    faction: "星穹",
    type: "unit",
    cost: 4,
    rarity: "稀有",
    attack: 4,
    health: 4,
    keywords: ["lifesteal"],
    traits: ["hunt"],
  },
  {
    id: "astral-prismatic-stag",
    name: "棱光星鹿",
    description: "嘲讽，护盾。它踏出的光环会成为同伴的避难所。",
    faction: "星穹",
    type: "unit",
    cost: 5,
    rarity: "史诗",
    attack: 4,
    health: 7,
    keywords: ["taunt", "shield"],
    traits: ["bulwark"],
  },
  {
    id: "astral-comet-rider",
    name: "彗星骑手",
    description: "冲锋，护盾。她以短暂燃烧换取一次完美抵达。",
    faction: "星穹",
    type: "unit",
    cost: 5,
    rarity: "史诗",
    attack: 5,
    health: 5,
    keywords: ["charge", "shield"],
    traits: ["swift"],
  },
  {
    id: "astral-galaxy-weaver",
    name: "银河编织者",
    description: "登场时，使一个友方单位获得 +2/+2。",
    faction: "星穹",
    type: "unit",
    cost: 5,
    rarity: "稀有",
    attack: 4,
    health: 6,
    traits: ["arcane"],
    target: "friendly-unit",
    onPlay: [{ kind: "buff", attack: 2, health: 2 }],
  },
  {
    id: "astral-lunar-vessel",
    name: "月相载体",
    description: "嘲讽。它用盈亏交替的外壳承受漫长战斗。",
    faction: "星穹",
    type: "unit",
    cost: 6,
    rarity: "普通",
    attack: 5,
    health: 8,
    keywords: ["taunt"],
    traits: ["bulwark", "craft"],
  },
  {
    id: "astral-deepspace-oracle",
    name: "深空神谕者",
    description: "登场时抽两张牌。它传回的答案总比问题更早抵达。",
    faction: "星穹",
    type: "unit",
    cost: 6,
    rarity: "史诗",
    attack: 5,
    health: 6,
    traits: ["arcane"],
    onPlay: [{ kind: "draw", count: 2 }],
  },
  {
    id: "astral-zenith-dragon",
    name: "天顶星龙",
    description: "护盾。它盘踞的高度没有阴影能够触及。",
    faction: "星穹",
    type: "unit",
    cost: 7,
    rarity: "史诗",
    attack: 7,
    health: 7,
    keywords: ["shield"],
    traits: ["hunt"],
  },
  {
    id: "astral-horizon-guardian",
    name: "视界守护者",
    description: "嘲讽。登场时，为一个友方角色恢复 4 点生命。",
    faction: "星穹",
    type: "unit",
    cost: 7,
    rarity: "稀有",
    attack: 6,
    health: 9,
    keywords: ["taunt"],
    traits: ["bulwark", "arcane"],
    target: "friendly-character",
    onPlay: [{ kind: "heal", amount: 4 }],
  },
  {
    id: "astral-cosmos-sovereign",
    name: "万象星主",
    description: "护盾。登场时抽两张牌。它以群星为冠，以长夜为座。",
    faction: "星穹",
    type: "unit",
    cost: 8,
    rarity: "传说",
    attack: 7,
    health: 10,
    keywords: ["shield"],
    traits: ["arcane", "craft"],
    onPlay: [{ kind: "draw", count: 2 }],
  },
  {
    id: "astral-infinite-observer",
    name: "无垠观测者",
    description: "嘲讽，护盾。登场时抽一张牌。它的凝视横跨无数纪元。",
    faction: "星穹",
    type: "unit",
    cost: 8,
    rarity: "传说",
    attack: 8,
    health: 8,
    keywords: ["taunt", "shield"],
    traits: ["bulwark", "arcane"],
    onPlay: [{ kind: "draw", count: 1 }],
  },

  // 星穹：10 张战术。
  {
    id: "astral-glimmer-echo",
    name: "微光回响",
    description: "为一个友方角色恢复 1 点生命。",
    faction: "星穹",
    type: "spell",
    cost: 0,
    rarity: "普通",
    school: "astral",
    target: "friendly-character",
    effect: [{ kind: "heal", amount: 1 }],
  },
  {
    id: "astral-chart-revelation",
    name: "星图启示",
    description: "发现一张星穹卡牌。星轨交会之处，答案自行显现。",
    faction: "星穹",
    type: "spell",
    cost: 1,
    rarity: "普通",
    school: "astral",
    target: "none",
    keywords: ["discover"],
    effect: [{ kind: "discover", choices: ["astral-stardust-familiar", "astral-chart-revelation", "astral-phase-shift"] }],
  },
  {
    id: "astral-phase-shift",
    name: "相位变形",
    description: "将一个敌方单位变形为苔径奔行兽。",
    faction: "星穹",
    type: "spell",
    cost: 4,
    rarity: "史诗",
    school: "astral",
    target: "enemy-unit",
    keywords: ["transform"],
    effect: [{ kind: "transform", cardId: "neutral-moss-runner" }],
  },
  {
    id: "astral-gentle-orbit",
    name: "温柔轨道",
    description: "为一个友方角色恢复 4 点生命。偏离战火的轨道容得下一次喘息。",
    faction: "星穹",
    type: "spell",
    cost: 2,
    rarity: "普通",
    school: "astral",
    target: "friendly-character",
    effect: [{ kind: "heal", amount: 4 }],
  },
  {
    id: "astral-lucid-script",
    name: "清醒星文",
    description: "抽一张牌，并为一个友方角色恢复 2 点生命。",
    faction: "星穹",
    type: "spell",
    cost: 2,
    rarity: "稀有",
    school: "astral",
    target: "friendly-character",
    effect: [
      { kind: "draw", count: 1 },
      { kind: "heal", amount: 2 },
    ],
  },
  {
    id: "astral-mirror-lesson",
    name: "镜像课程",
    description: "使一个友方单位获得 +1/+3。镜中的自己总能指出防守缺口。",
    faction: "星穹",
    type: "spell",
    cost: 3,
    rarity: "稀有",
    school: "astral",
    target: "friendly-unit",
    effect: [{ kind: "buff", attack: 1, health: 3 }],
  },
  {
    id: "astral-constellation-call",
    name: "星群呼唤",
    description: "奥秘：当敌方召唤单位时，为你的核心恢复 3 点生命。",
    faction: "星穹",
    type: "spell",
    cost: 3,
    rarity: "稀有",
    school: "astral",
    target: "none",
    keywords: ["secret"],
    effect: [{
      kind: "secret",
      secretId: "astral-constellation-call",
      trigger: "opponent-summons-unit",
      effect: { kind: "heal-friendly-hero", amount: 3 },
    }],
  },
  {
    id: "astral-meteor-pin",
    name: "流星钉刺",
    description: "对一个敌方角色造成 4 点伤害。一线星火将目标钉在既定轨迹。",
    faction: "星穹",
    type: "spell",
    cost: 4,
    rarity: "稀有",
    school: "astral",
    target: "enemy-character",
    effect: [{ kind: "damage", amount: 4 }],
  },
  {
    id: "astral-deep-divination",
    name: "深空占卜",
    description: "抽三张牌。",
    faction: "星穹",
    type: "spell",
    cost: 5,
    rarity: "史诗",
    school: "astral",
    target: "none",
    effect: [{ kind: "draw", count: 3 }],
  },
  {
    id: "astral-supernova-ripple",
    name: "超新星权杖",
    description: "武器：4 点攻击，3 点耐久。",
    faction: "星穹",
    type: "weapon",
    cost: 7,
    rarity: "史诗",
    attack: 4,
    durability: 3,
  },
]);
