import type { CardDefinition } from "./types.ts";

const VERDANT_CARDS: readonly CardDefinition[] = [
  {
    id: "verdant-spore-scout",
    name: "孢芽斥候",
    description: "林地中最不起眼，也最可靠的先行者。",
    faction: "苍林",
    type: "unit",
    cost: 0,
    rarity: "普通",
    attack: 1,
    health: 1,
    traits: ["hunt"],
  },
  {
    id: "verdant-dewleaf-apprentice",
    name: "露叶学徒",
    description: "汲取。登场时为一个友方角色恢复 1 点生命。",
    faction: "苍林",
    type: "unit",
    cost: 1,
    rarity: "普通",
    attack: 1,
    health: 2,
    keywords: ["lifesteal"],
    traits: ["arcane"],
    target: "friendly-character",
    onPlay: [{ kind: "heal", amount: 1 }],
  },
  {
    id: "verdant-mossback-keeper",
    name: "苔背守苗人",
    description: "嘲讽。以厚实苔甲护住新生幼苗。",
    faction: "苍林",
    type: "unit",
    cost: 1,
    rarity: "普通",
    attack: 1,
    health: 3,
    keywords: ["taunt"],
    traits: ["bulwark"],
  },
  {
    id: "verdant-thornstep-runner",
    name: "棘步疾行者",
    description: "冲锋。藤棘会为它让开最短的道路。",
    faction: "苍林",
    type: "unit",
    cost: 1,
    rarity: "普通",
    attack: 2,
    health: 1,
    keywords: ["charge"],
    traits: ["swift", "hunt"],
  },
  {
    id: "verdant-seedsong-sprite",
    name: "种歌精灵",
    description: "登场时抽一张牌。它记得每颗种子的歌。",
    faction: "苍林",
    type: "unit",
    cost: 1,
    rarity: "稀有",
    attack: 1,
    health: 2,
    traits: ["arcane"],
    onPlay: [{ kind: "draw", count: 1 }],
  },
  {
    id: "verdant-antler-pathfinder",
    name: "青角寻径者",
    description: "循着花粉与月光寻找隐秘林道。",
    faction: "苍林",
    type: "unit",
    cost: 2,
    rarity: "普通",
    attack: 2,
    health: 3,
    traits: ["hunt", "craft"],
  },
  {
    id: "verdant-barkshield-sentinel",
    name: "树甲哨卫",
    description: "嘲讽。年轮就是它从不后退的证明。",
    faction: "苍林",
    type: "unit",
    cost: 2,
    rarity: "普通",
    attack: 2,
    health: 4,
    keywords: ["taunt"],
    traits: ["bulwark"],
  },
  {
    id: "verdant-nectar-mender",
    name: "蜜露愈师",
    description: "汲取。登场时为一个友方角色恢复 2 点生命。",
    faction: "苍林",
    type: "unit",
    cost: 2,
    rarity: "稀有",
    attack: 2,
    health: 3,
    keywords: ["lifesteal"],
    traits: ["arcane"],
    target: "friendly-character",
    onPlay: [{ kind: "heal", amount: 2 }],
  },
  {
    id: "verdant-vinewhip-duelist",
    name: "藤鞭斗士",
    description: "激昂。每一道伤痕都会催生新的藤刺。",
    faction: "苍林",
    type: "unit",
    cost: 2,
    rarity: "普通",
    attack: 3,
    health: 2,
    keywords: ["fury"],
    traits: ["swift"],
  },
  {
    id: "verdant-canopy-archer",
    name: "冠层猎弓手",
    description: "登场时对一个敌方角色造成 1 点伤害。",
    faction: "苍林",
    type: "unit",
    cost: 2,
    rarity: "稀有",
    attack: 3,
    health: 2,
    traits: ["hunt"],
    target: "enemy-character",
    onPlay: [{ kind: "damage", amount: 1 }],
  },
  {
    id: "verdant-rootweave-artisan",
    name: "盘根编甲师",
    description: "护盾。将活根编织成会自行愈合的甲胄。",
    faction: "苍林",
    type: "unit",
    cost: 2,
    rarity: "稀有",
    attack: 2,
    health: 3,
    keywords: ["shield"],
    traits: ["craft", "bulwark"],
  },
  {
    id: "verdant-bloom-banner",
    name: "繁花执旗者",
    description: "登场时使一个友方单位获得 +1/+1。",
    faction: "苍林",
    type: "unit",
    cost: 3,
    rarity: "稀有",
    attack: 3,
    health: 4,
    traits: ["arcane", "bulwark"],
    target: "friendly-unit",
    onPlay: [{ kind: "buff", attack: 1, health: 1 }],
  },
  {
    id: "verdant-moonfern-stalker",
    name: "月蕨追猎者",
    description: "冲锋。月色落下之前，猎物只会看见一道绿影。",
    faction: "苍林",
    type: "unit",
    cost: 3,
    rarity: "普通",
    attack: 4,
    health: 3,
    keywords: ["charge"],
    traits: ["hunt", "swift"],
  },
  {
    id: "verdant-grovebond-shaman",
    name: "林契萨满",
    description: "登场时为一个友方角色恢复 3 点生命。",
    faction: "苍林",
    type: "unit",
    cost: 3,
    rarity: "稀有",
    attack: 3,
    health: 4,
    traits: ["arcane"],
    target: "friendly-character",
    onPlay: [{ kind: "heal", amount: 3 }],
  },
  {
    id: "verdant-briarhide-boar",
    name: "荆皮战野猪",
    description: "嘲讽，激昂。它的冲撞会让整片灌木一同震颤。",
    faction: "苍林",
    type: "unit",
    cost: 3,
    rarity: "史诗",
    attack: 4,
    health: 5,
    keywords: ["taunt", "fury"],
    traits: ["bulwark", "hunt"],
  },
  {
    id: "verdant-ancient-bough-guardian",
    name: "古枝壁垒",
    description: "嘲讽，护盾。它曾为三代森林挡下烈火。",
    faction: "苍林",
    type: "unit",
    cost: 4,
    rarity: "史诗",
    attack: 3,
    health: 7,
    keywords: ["taunt", "shield"],
    traits: ["bulwark"],
  },
  {
    id: "verdant-dawnpetal-stag",
    name: "曦瓣灵鹿",
    description: "汲取。踏过之处会在破晓时开花。",
    faction: "苍林",
    type: "unit",
    cost: 4,
    rarity: "史诗",
    attack: 5,
    health: 5,
    keywords: ["lifesteal"],
    traits: ["hunt", "arcane"],
  },
  {
    id: "verdant-seedvault-engineer",
    name: "种库构筑师",
    description: "护盾。它用远古种壳搭建会呼吸的工事。",
    faction: "苍林",
    type: "unit",
    cost: 5,
    rarity: "史诗",
    attack: 4,
    health: 6,
    keywords: ["shield"],
    traits: ["craft", "bulwark"],
  },
  {
    id: "verdant-thousandleaf-titan",
    name: "千叶巨灵",
    description: "嘲讽。万千叶片在它肩头汇成不破冠冕。",
    faction: "苍林",
    type: "unit",
    cost: 6,
    rarity: "史诗",
    attack: 5,
    health: 9,
    keywords: ["taunt"],
    traits: ["bulwark", "arcane"],
  },
  {
    id: "verdant-worldroot-matriarch",
    name: "世界根母",
    description: "嘲讽，汲取。登场时为一个友方角色恢复 5 点生命。",
    faction: "苍林",
    type: "unit",
    cost: 7,
    rarity: "传说",
    attack: 6,
    health: 10,
    keywords: ["taunt", "lifesteal"],
    traits: ["bulwark", "arcane"],
    target: "friendly-character",
    onPlay: [{ kind: "heal", amount: 5 }],
  },
  {
    id: "verdant-sprout-pact",
    name: "萌芽之约",
    description: "使一个友方单位获得 +0/+1。",
    faction: "苍林",
    type: "spell",
    cost: 0,
    rarity: "普通",
    school: "verdant",
    target: "friendly-unit",
    effect: [{ kind: "buff", attack: 0, health: 1 }],
  },
  {
    id: "verdant-morning-dew",
    name: "林间晨露",
    description: "为一个友方角色恢复 3 点生命。",
    faction: "苍林",
    type: "spell",
    cost: 1,
    rarity: "普通",
    school: "verdant",
    target: "friendly-character",
    effect: [{ kind: "heal", amount: 3 }],
  },
  {
    id: "verdant-thorn-lash",
    name: "荆藤抽击",
    description: "对一个敌方角色造成 2 点伤害。",
    faction: "苍林",
    type: "spell",
    cost: 1,
    rarity: "普通",
    school: "verdant",
    target: "enemy-character",
    effect: [{ kind: "damage", amount: 2 }],
  },
  {
    id: "verdant-rooting-rite",
    name: "扎根仪式",
    description: "使一个友方单位获得 +1/+3。",
    faction: "苍林",
    type: "spell",
    cost: 2,
    rarity: "普通",
    school: "verdant",
    target: "friendly-unit",
    effect: [{ kind: "buff", attack: 1, health: 3 }],
  },
  {
    id: "verdant-pathfinder-call",
    name: "寻径者号角",
    description: "抽两张牌。",
    faction: "苍林",
    type: "spell",
    cost: 3,
    rarity: "稀有",
    school: "verdant",
    target: "none",
    effect: [{ kind: "draw", count: 2 }],
  },
  {
    id: "verdant-canopy-ambush",
    name: "冠林伏击",
    description: "对一个随机敌方角色造成 3 点伤害。",
    faction: "苍林",
    type: "spell",
    cost: 3,
    rarity: "稀有",
    school: "verdant",
    target: "none",
    effect: [{ kind: "random-enemy-damage", amount: 3 }],
  },
  {
    id: "verdant-seedburst",
    name: "种荚迸裂",
    description: "召唤两个孢芽斥候。",
    faction: "苍林",
    type: "spell",
    cost: 3,
    rarity: "史诗",
    school: "verdant",
    target: "none",
    effect: [{ kind: "summon", cardId: "verdant-spore-scout", count: 2 }],
  },
  {
    id: "verdant-wild-regrowth",
    name: "野性复苏",
    description: "为一个友方角色恢复 7 点生命。",
    faction: "苍林",
    type: "spell",
    cost: 4,
    rarity: "稀有",
    school: "verdant",
    target: "friendly-character",
    effect: [{ kind: "heal", amount: 7 }],
  },
  {
    id: "verdant-flourishing-chorus",
    name: "繁盛合唱",
    description: "使一个友方单位获得 +3/+4。",
    faction: "苍林",
    type: "spell",
    cost: 5,
    rarity: "史诗",
    school: "verdant",
    target: "friendly-unit",
    effect: [{ kind: "buff", attack: 3, health: 4 }],
  },
  {
    id: "verdant-all-roots-as-one",
    name: "万根藤鞭",
    description: "武器：3 点攻击，4 点耐久。",
    faction: "苍林",
    type: "weapon",
    cost: 8,
    rarity: "传说",
    attack: 3,
    durability: 4,
  },
];

const STORM_CARDS: readonly CardDefinition[] = [
  {
    id: "storm-spark-mite",
    name: "火花螨",
    description: "一团装进黄铜外壳的活跃电火花。",
    faction: "雷铸",
    type: "unit",
    cost: 0,
    rarity: "普通",
    attack: 1,
    health: 1,
    traits: ["craft"],
  },
  {
    id: "storm-coppercoil-cadet",
    name: "铜线圈新兵",
    description: "激昂。每次受击都会让线圈转得更快。",
    faction: "雷铸",
    type: "unit",
    cost: 1,
    rarity: "普通",
    attack: 2,
    health: 1,
    keywords: ["fury"],
    traits: ["craft", "swift"],
  },
  {
    id: "storm-lightning-courier",
    name: "闪电信使",
    description: "冲锋。讯息尚未发出，它已经抵达。",
    faction: "雷铸",
    type: "unit",
    cost: 1,
    rarity: "普通",
    attack: 2,
    health: 1,
    keywords: ["charge"],
    traits: ["swift"],
  },
  {
    id: "storm-capacitor-sentry",
    name: "蓄能哨机",
    description: "护盾。待机时会默默收集空气里的电荷。",
    faction: "雷铸",
    type: "unit",
    cost: 1,
    rarity: "普通",
    attack: 1,
    health: 3,
    keywords: ["shield"],
    traits: ["craft", "bulwark"],
  },
  {
    id: "storm-ironcloud-scavenger",
    name: "铁云拾荒客",
    description: "登场时抽一张牌。它总能从雷雨后捡到好东西。",
    faction: "雷铸",
    type: "unit",
    cost: 1,
    rarity: "稀有",
    attack: 1,
    health: 2,
    traits: ["craft", "hunt"],
    onPlay: [{ kind: "draw", count: 1 }],
  },
  {
    id: "storm-voltedge-duelist",
    name: "伏刃决斗家",
    description: "激昂。剑锋上的电弧随怒意一同增长。",
    faction: "雷铸",
    type: "unit",
    cost: 2,
    rarity: "普通",
    attack: 3,
    health: 2,
    keywords: ["fury"],
    traits: ["swift"],
  },
  {
    id: "storm-relay-shieldguard",
    name: "继电盾卫",
    description: "嘲讽，护盾。它是雷铸阵线最稳定的接地点。",
    faction: "雷铸",
    type: "unit",
    cost: 2,
    rarity: "稀有",
    attack: 2,
    health: 3,
    keywords: ["taunt", "shield"],
    traits: ["bulwark", "craft"],
  },
  {
    id: "storm-coil-sage",
    name: "线圈贤者",
    description: "登场时对一个随机敌方角色造成 1 点伤害。",
    faction: "雷铸",
    type: "unit",
    cost: 2,
    rarity: "稀有",
    attack: 2,
    health: 3,
    traits: ["arcane", "craft"],
    onPlay: [{ kind: "random-enemy-damage", amount: 1 }],
  },
  {
    id: "storm-thundertrack-hound",
    name: "逐雷猎犬",
    description: "冲锋。它只追逐刚刚落下的那道闪电。",
    faction: "雷铸",
    type: "unit",
    cost: 2,
    rarity: "普通",
    attack: 3,
    health: 2,
    keywords: ["charge"],
    traits: ["hunt", "swift"],
  },
  {
    id: "storm-magnetic-salvager",
    name: "磁流回收者",
    description: "汲取。它会把逸散的能量重新导回核心。",
    faction: "雷铸",
    type: "unit",
    cost: 2,
    rarity: "普通",
    attack: 2,
    health: 3,
    keywords: ["lifesteal"],
    traits: ["craft"],
  },
  {
    id: "storm-forge-armorer",
    name: "雷炉铸甲师",
    description: "登场时使一个友方单位获得 +1/+1。",
    faction: "雷铸",
    type: "unit",
    cost: 3,
    rarity: "稀有",
    attack: 3,
    health: 4,
    traits: ["craft", "bulwark"],
    target: "friendly-unit",
    onPlay: [{ kind: "buff", attack: 1, health: 1 }],
  },
  {
    id: "storm-arcspark-marksman",
    name: "弧光神射手",
    description: "登场时对一个随机敌方角色造成 1 点伤害。",
    faction: "雷铸",
    type: "unit",
    cost: 3,
    rarity: "稀有",
    attack: 4,
    health: 3,
    traits: ["hunt"],
    onPlay: [{ kind: "random-enemy-damage", amount: 1 }],
  },
  {
    id: "storm-turbine-lancer",
    name: "涡轮枪骑",
    description: "冲锋，激昂。加速装置从来没有低速档。",
    faction: "雷铸",
    type: "unit",
    cost: 3,
    rarity: "史诗",
    attack: 4,
    health: 3,
    keywords: ["charge", "fury"],
    traits: ["swift", "craft"],
  },
  {
    id: "storm-overcharge-golem",
    name: "过载魔像",
    description: "激昂。警示灯越亮，它的拳头就越重。",
    faction: "雷铸",
    type: "unit",
    cost: 3,
    rarity: "普通",
    attack: 4,
    health: 5,
    keywords: ["fury"],
    traits: ["craft"],
  },
  {
    id: "storm-cloudbreaker-captain",
    name: "破云舰长",
    description: "护盾。登场时抽一张牌。",
    faction: "雷铸",
    type: "unit",
    cost: 3,
    rarity: "史诗",
    attack: 3,
    health: 5,
    keywords: ["shield"],
    traits: ["arcane", "craft"],
    onPlay: [{ kind: "draw", count: 1 }],
  },
  {
    id: "storm-tempest-bulwark",
    name: "风暴壁垒机",
    description: "嘲讽，护盾。雷鸣在它的装甲内变得沉默。",
    faction: "雷铸",
    type: "unit",
    cost: 4,
    rarity: "史诗",
    attack: 3,
    health: 7,
    keywords: ["taunt", "shield"],
    traits: ["bulwark", "craft"],
  },
  {
    id: "storm-chainbolt-colossus",
    name: "链雷巨像",
    description: "登场时对一个随机敌方角色造成 2 点伤害。",
    faction: "雷铸",
    type: "unit",
    cost: 4,
    rarity: "史诗",
    attack: 5,
    health: 5,
    traits: ["craft", "arcane"],
    onPlay: [{ kind: "random-enemy-damage", amount: 2 }],
  },
  {
    id: "storm-skyrail-ace",
    name: "天轨王牌",
    description: "冲锋。从云端俯冲时，它与雷声同时抵达。",
    faction: "雷铸",
    type: "unit",
    cost: 4,
    rarity: "史诗",
    attack: 5,
    health: 4,
    keywords: ["charge"],
    traits: ["hunt", "swift"],
  },
  {
    id: "storm-living-dynamo",
    name: "活体雷轮",
    description: "护盾，激昂。没有人知道究竟是谁启动了它。",
    faction: "雷铸",
    type: "unit",
    cost: 5,
    rarity: "史诗",
    attack: 6,
    health: 6,
    keywords: ["shield", "fury"],
    traits: ["craft", "arcane"],
  },
  {
    id: "storm-skyforge-thunderking",
    name: "天铸雷王",
    description: "护盾，激昂。登场时对一个随机敌方角色造成 4 点伤害。",
    faction: "雷铸",
    type: "unit",
    cost: 7,
    rarity: "传说",
    attack: 7,
    health: 8,
    keywords: ["shield", "fury"],
    traits: ["craft", "bulwark"],
    onPlay: [{ kind: "random-enemy-damage", amount: 4 }],
  },
  {
    id: "storm-static-spark",
    name: "游离电火",
    description: "对一个随机敌方角色造成 1 点伤害。",
    faction: "雷铸",
    type: "spell",
    cost: 0,
    rarity: "普通",
    school: "storm",
    target: "none",
    effect: [{ kind: "random-enemy-damage", amount: 1 }],
  },
  {
    id: "storm-bolt-calibration",
    name: "雷栓校准",
    description: "对一个敌方角色造成 2 点伤害。",
    faction: "雷铸",
    type: "spell",
    cost: 1,
    rarity: "普通",
    school: "storm",
    target: "enemy-character",
    effect: [{ kind: "damage", amount: 2 }],
  },
  {
    id: "storm-emergency-plating",
    name: "应急镀层",
    description: "使一个友方单位获得 +0/+2。",
    faction: "雷铸",
    type: "spell",
    cost: 1,
    rarity: "普通",
    school: "storm",
    target: "friendly-unit",
    effect: [{ kind: "buff", attack: 0, health: 2 }],
  },
  {
    id: "storm-capacitor-draw",
    name: "电容抽载",
    description: "抽一张牌。",
    faction: "雷铸",
    type: "spell",
    cost: 2,
    rarity: "普通",
    school: "storm",
    target: "none",
    effect: [{ kind: "draw", count: 1 }],
  },
  {
    id: "storm-chain-discharge",
    name: "链式放电",
    description: "对一个随机敌方角色造成 3 点伤害。",
    faction: "雷铸",
    type: "spell",
    cost: 3,
    rarity: "稀有",
    school: "storm",
    target: "none",
    effect: [{ kind: "random-enemy-damage", amount: 3 }],
  },
  {
    id: "storm-forge-temper",
    name: "雷炉淬炼",
    description: "使一个友方单位获得 +2/+2。",
    faction: "雷铸",
    type: "spell",
    cost: 3,
    rarity: "稀有",
    school: "storm",
    target: "friendly-unit",
    effect: [{ kind: "buff", attack: 2, health: 2 }],
  },
  {
    id: "storm-drone-deployment",
    name: "火花机群",
    description: "召唤两个火花螨。",
    faction: "雷铸",
    type: "spell",
    cost: 3,
    rarity: "史诗",
    school: "storm",
    target: "none",
    effect: [{ kind: "summon", cardId: "storm-spark-mite", count: 2 }],
  },
  {
    id: "storm-thunder-salvo",
    name: "雷云齐射",
    description: "对一个随机敌方角色造成 4 点伤害。",
    faction: "雷铸",
    type: "spell",
    cost: 4,
    rarity: "稀有",
    school: "storm",
    target: "none",
    effect: [{ kind: "random-enemy-damage", amount: 4 }],
  },
  {
    id: "storm-overload-reactor",
    name: "过载反应炉",
    description: "对一个敌方角色造成 5 点伤害，并抽一张牌。",
    faction: "雷铸",
    type: "spell",
    cost: 5,
    rarity: "史诗",
    school: "storm",
    target: "enemy-character",
    effect: [
      { kind: "damage", amount: 5 },
      { kind: "draw", count: 1 },
    ],
  },
  {
    id: "storm-ninefold-tempest",
    name: "九霄雷锤",
    description: "武器：7 点攻击，2 点耐久。",
    faction: "雷铸",
    type: "weapon",
    cost: 8,
    rarity: "传说",
    attack: 7,
    durability: 2,
  },
];

export const VERDANT_STORM_CARDS: readonly CardDefinition[] = Object.freeze([
  ...VERDANT_CARDS,
  ...STORM_CARDS,
]);
